1) additional libs for AIX. still need to test it :) 2) --with-filterdb arg added to specify filter's db

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -776,6 +776,10 @@ Fine tuning of the installation directories:
 _ACEOF
 
   cat <<\_ACEOF
+
+System types:
+  --build=BUILD     configure for building on BUILD [guessed]
+  --host=HOST       cross-compile to build programs to run on HOST [BUILD]
 _ACEOF
 fi
 
@@ -801,6 +805,7 @@ Optional Packages:
   --with-cosigncadir=DIR  default cosign CA dir location
   --with-cosigncert=FILE  default cosign cert file location
   --with-cosignkey=FILE   default cosign key file location
+  --with-filterdb=DIR     default cosign filter database storage
   --with-ssl=DIR          path to ssl
   --with-apache-apxs=FILE path to Apache apxs program
 
@@ -2366,6 +2371,61 @@ done
 test -n "$YACC" || YACC="yacc"
 
 
+# Make sure we can run config.sub.
+$ac_config_sub sun4 >/dev/null 2>&1 ||
+  { { echo "$as_me:$LINENO: error: cannot run $ac_config_sub" >&5
+echo "$as_me: error: cannot run $ac_config_sub" >&2;}
+   { (exit 1); exit 1; }; }
+
+echo "$as_me:$LINENO: checking build system type" >&5
+echo $ECHO_N "checking build system type... $ECHO_C" >&6
+if test "${ac_cv_build+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_build_alias=$build_alias
+test -z "$ac_cv_build_alias" &&
+  ac_cv_build_alias=`$ac_config_guess`
+test -z "$ac_cv_build_alias" &&
+  { { echo "$as_me:$LINENO: error: cannot guess build type; you must specify one" >&5
+echo "$as_me: error: cannot guess build type; you must specify one" >&2;}
+   { (exit 1); exit 1; }; }
+ac_cv_build=`$ac_config_sub $ac_cv_build_alias` ||
+  { { echo "$as_me:$LINENO: error: $ac_config_sub $ac_cv_build_alias failed" >&5
+echo "$as_me: error: $ac_config_sub $ac_cv_build_alias failed" >&2;}
+   { (exit 1); exit 1; }; }
+
+fi
+echo "$as_me:$LINENO: result: $ac_cv_build" >&5
+echo "${ECHO_T}$ac_cv_build" >&6
+build=$ac_cv_build
+build_cpu=`echo $ac_cv_build | sed 's/^\([^-]*\)-\([^-]*\)-\(.*\)$/\1/'`
+build_vendor=`echo $ac_cv_build | sed 's/^\([^-]*\)-\([^-]*\)-\(.*\)$/\2/'`
+build_os=`echo $ac_cv_build | sed 's/^\([^-]*\)-\([^-]*\)-\(.*\)$/\3/'`
+
+
+echo "$as_me:$LINENO: checking host system type" >&5
+echo $ECHO_N "checking host system type... $ECHO_C" >&6
+if test "${ac_cv_host+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_host_alias=$host_alias
+test -z "$ac_cv_host_alias" &&
+  ac_cv_host_alias=$ac_cv_build_alias
+ac_cv_host=`$ac_config_sub $ac_cv_host_alias` ||
+  { { echo "$as_me:$LINENO: error: $ac_config_sub $ac_cv_host_alias failed" >&5
+echo "$as_me: error: $ac_config_sub $ac_cv_host_alias failed" >&2;}
+   { (exit 1); exit 1; }; }
+
+fi
+echo "$as_me:$LINENO: result: $ac_cv_host" >&5
+echo "${ECHO_T}$ac_cv_host" >&6
+host=$ac_cv_host
+host_cpu=`echo $ac_cv_host | sed 's/^\([^-]*\)-\([^-]*\)-\(.*\)$/\1/'`
+host_vendor=`echo $ac_cv_host | sed 's/^\([^-]*\)-\([^-]*\)-\(.*\)$/\2/'`
+host_os=`echo $ac_cv_host | sed 's/^\([^-]*\)-\([^-]*\)-\(.*\)$/\3/'`
+
+
+
 # Checks for libraries.
 
 echo "$as_me:$LINENO: checking for inet_ntoa in -lnsl" >&5
@@ -2653,6 +2713,16 @@ fi;
 
 
 
+# Check whether --with-filterdb or --without-filterdb was given.
+if test "${with_filterdb+set}" = set; then
+  withval="$with_filterdb"
+  filterdb="$withval"
+else
+  filterdb="/var/cosign/filter"
+fi;
+
+
+
     echo "$as_me:$LINENO: checking for ssl" >&5
 echo $ECHO_N "checking for ssl... $ECHO_C" >&6
     ssldirs="/usr/local/openssl /usr/lib/openssl /usr/openssl \
@@ -2686,6 +2756,13 @@ fi
 echo "$as_me: error: cannot find ssl libraries" >&2;}
    { (exit 1); exit 1; }; }
     fi
+    if test "X$host_os" = "Xaix" ; then
+	ADDLIBS="-lssl -lcrypto";
+
+	ADDLDFLAGS="-L$ac_cv_path_ssl/lib";
+
+    fi
+
     CPPFLAGS="$CPPFLAGS -I$ac_cv_path_ssl/include";
     TLSDEFS=-DTLS;
 
@@ -2742,6 +2819,7 @@ fi
         else
             APACHECTL="${APXS_SBINDIR}/${APXS_TARGET}ctl"
         fi
+
 
 
 
@@ -3393,6 +3471,14 @@ s,@LEX@,$LEX,;t t
 s,@LEXLIB@,$LEXLIB,;t t
 s,@LEX_OUTPUT_ROOT@,$LEX_OUTPUT_ROOT,;t t
 s,@YACC@,$YACC,;t t
+s,@build@,$build,;t t
+s,@build_cpu@,$build_cpu,;t t
+s,@build_vendor@,$build_vendor,;t t
+s,@build_os@,$build_os,;t t
+s,@host@,$host,;t t
+s,@host_cpu@,$host_cpu,;t t
+s,@host_vendor@,$host_vendor,;t t
+s,@host_os@,$host_os,;t t
 s,@KRBDEFS@,$KRBDEFS,;t t
 s,@KINC@,$KINC,;t t
 s,@KLIBS@,$KLIBS,;t t
@@ -3413,6 +3499,9 @@ s,@cosignconf@,$cosignconf,;t t
 s,@cosigncadir@,$cosigncadir,;t t
 s,@cosigncert@,$cosigncert,;t t
 s,@cosignkey@,$cosignkey,;t t
+s,@filterdb@,$filterdb,;t t
+s,@ADDLIBS@,$ADDLIBS,;t t
+s,@ADDLDFLAGS@,$ADDLDFLAGS,;t t
 s,@TLSDEFS@,$TLSDEFS,;t t
 s,@HAVE_SSL@,$HAVE_SSL,;t t
 s,@APXS@,$APXS,;t t
